import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';
const assert=(c,m)=>{if(!c)throw new Error(m)};
let code=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8').replace(/\ninit\(\);\s*$/,'\n');
const k=JSON.parse(fs.readFileSync(new URL('../data/cat-knowledge-v0.7.json',import.meta.url),'utf8'));
const ctx={console,crypto:crypto.webcrypto,setTimeout,clearTimeout,structuredClone,Intl,Date,Math,JSON,Map,Set,URL,Blob};vm.createContext(ctx);vm.runInContext(code,ctx);const run=s=>vm.runInContext(s,ctx);run(`knowledge=${JSON.stringify(k)};`);
run(`state=migrateState({schemaVersion:3,pets:[{id:'p',name:'Cat',species:'cat',sex:'male',birthDate:'2020-01-01'}],episodes:[{id:'e',petId:'p',title:'Old',start:'2025-01-01T00:00:00Z',end:null,status:'open'}],observations:[],clinicalMeasurements:[],diets:[],settings:{activePetId:'p',activeEpisodeId:'e'}});`);
assert(run('state.schemaVersion')===7,'state schema v7');assert(run('Array.isArray(state.diagnoses)'),'diagnoses created');assert(run('Array.isArray(state.treatments)'),'treatments created');assert(run('Array.isArray(state.studies)'),'studies created');assert(run('Array.isArray(state.episodes[0].linkedEpisodeIds)'),'episode links created');assert(['live','retrospective'].includes(run('state.episodes[0].trackingMode')),'tracking mode created');assert(run('state.episodes[0].monitoringCadence')==='standard','monitoring cadence created');assert(run("['latest_evidence','current_time'].includes(state.episodes[0].entryDateMode)"),'entry date mode created');
// Diet remains context only.
run(`state.observations=[{id:'o',episodeId:'e',findingId:'weight_loss',present:true,time:'2025-01-02T00:00:00Z',severity:'medium',confidence:'high',notes:''}];`);const before=run(`infer().map(x=>x.score).join(',')`);run(`state.diets.push({id:'d',petId:'p',product:'food',startDate:'2025-01-01',endDate:'',nutrientBasis:'as_fed',carbs:'1'})`);const after=run(`infer().map(x=>x.score).join(',')`);assert(before===after,'diet not inferential');
run(`state.treatments.push({id:'tx',petId:'p',episodeId:'e',name:'therapy',type:'medication',start:'2025-01-02T00:00:00Z',response:'improved'});state.studies.push({id:'st',petId:'p',episodeId:'e',type:'ultrasound',time:'2025-01-03T00:00:00Z',interpretation:'abnormal',summary:'demo'})`);const afterContext=run(`infer().map(x=>x.score).join(',')`);assert(before===afterContext,'treatment/study context not inferential');
// Prior diagnoses are explicit and opt-in.
const base=run(`infer().find(x=>x.id==='chronic_kidney_disease').score`);run(`state.diagnoses.push({id:'dx',petId:'p',conditionId:'chronic_kidney_disease',status:'confirmed_active',date:'2024-01-01',source:'veterinarian',useInModel:true,notes:''})`);const boosted=run(`infer().find(x=>x.id==='chronic_kidney_disease').score`);assert(boosted>base,'confirmed diagnosis changes prior context');
// Linked episodes are separate until explicitly linked.
run(`state.diagnoses=[]; const old=makeEpisode('p','Prior','2024-01-01T00:00:00Z');old.id='old';state.episodes.push(old);state.observations.push({id:'old-o',episodeId:'old',findingId:'thirst_increased',present:true,time:'2024-01-02T00:00:00Z',severity:'high',confidence:'high',notes:''});`);assert(!run(`modelEvidence().some(e=>e.sourceScope==='linked')`),'history not auto-linked');run(`state.episodes.find(e=>e.id==='e').linkedEpisodeIds=['old']`);const hist=run(`modelEvidence().filter(e=>e.sourceScope==='linked')`);assert(hist.length===1&&hist[0].weight<1,'linked history enters at reduced weight');
// Episode bounds support retrospective repair.
run(`state.observations.push({id:'oldest',episodeId:'e',findingId:'energy_low',present:true,time:'2023-12-01T00:00:00Z',severity:'medium',confidence:'high',notes:''})`);assert(run(`episodeEvidenceBounds(state.episodes.find(e=>e.id==='e')).first`).startsWith('2023-12-01'),'evidence bounds use raw dates');
assert(run(`episodeAnalysisStart(state.episodes.find(e=>e.id==='e'))`).startsWith('2023-12-01'),'analysis start automatically respects earlier retrospective evidence');
const legacyStatus=run(`migrateState({schemaVersion:4,pets:[{id:'q',name:'Legacy',species:'cat'}],episodes:[{id:'qe',petId:'q',title:'Old',start:'2025-01-01T00:00:00Z',status:'open'}],observations:[{id:'qo',episodeId:'qe',findingId:'weight_loss',present:true,time:'2025-01-01T01:00:00Z'}],clinicalMeasurements:[],diets:[],diagnoses:[],settings:{activePetId:'q',activeEpisodeId:'qe'}}).observations[0].status`);assert(legacyStatus==='present','legacy observation status migrated');
const contextHtml=run(`renderContextPage()`);assert(contextHtml.includes('data-add-treatment')&&contextHtml.includes('data-add-study')&&contextHtml.includes('LONGITUDINAL TRENDS'),'context UI exposes trends, treatments and studies');
const historyHtml=run(`renderHistoryPage()`);assert(historyHtml.includes('data-add-diagnosis')&&historyHtml.includes('data-link-episode'),'history UI exposes diagnosis and linked-episode controls');
const modelHtml=run(`renderModelPage()`);assert(modelHtml.includes('Derived evidence contribution')&&modelHtml.includes('Inference architecture'),'model UI exposes inference audit');
const monitoringHtml=run(`renderMonitoringPage()`);assert(monitoringHtml.includes('REASSESSMENT QUEUE')&&monitoringHtml.includes('NEW INFORMATION'),'monitoring UI exposes reassessment and new-information lanes');
console.log('PASS migration to state schema v7');
console.log('PASS diet/treatment/study context isolation');
console.log('PASS diagnosis prior context');
console.log('PASS optional linked-history evidence');
console.log('PASS retrospective episode-date bounds');
// Legacy open episodes with evidence far before the recorded episode start migrate to retrospective tracking.
const retro=run(`migrateState({schemaVersion:5,pets:[{id:'r',name:'Retro',species:'cat'}],episodes:[{id:'re',petId:'r',title:'Historical',start:'2026-09-26T00:00:00Z',status:'open'}],observations:[{id:'ro',episodeId:'re',findingId:'thirst_increased',present:true,status:'present',time:'2025-12-01T00:00:00Z',severity:'medium',confidence:'high'}],clinicalMeasurements:[],diets:[],diagnoses:[],treatments:[],studies:[],settings:{activePetId:'r',activeEpisodeId:'re'}})`);assert(retro.episodes[0].trackingMode==='retrospective','historical evidence infers retrospective mode');assert(retro.episodes[0].entryDateMode==='latest_evidence','retrospective migration defaults new entries to latest evidence');
run(`state=${JSON.stringify(retro)};`);assert(run(`episodeMonitoringReference()`).startsWith('2025-12-01'),'retrospective monitoring reference uses latest evidence rather than wall clock');assert(run(`episodeEntryDefaultTime()`).startsWith('2025-12-01'),'retrospective entry default uses latest recorded evidence');
const retroForm=run(`logFormHtml(null,'retroForm')`);assert(retroForm.includes('Use latest episode entry')&&retroForm.includes('2025-12-01T00:00'),'observation form exposes latest-entry date helper and historical default');
assert(run(`clinicalFormHtml(null)`).includes('Use latest episode entry'),'clinical result form exposes historical date helper');assert(run(`treatmentFormHtml(null)`).includes('Use latest episode entry'),'treatment form exposes historical date helper');assert(run(`studyFormHtml(null)`).includes('Use latest episode entry'),'diagnostic study form exposes historical date helper');
const retroScore=run(`infer().map(x=>x.score).join(',')`);run(`state.episodes[0].entryDateMode='current_time'`);const dateModeScore=run(`infer().map(x=>x.score).join(',')`);assert(retroScore===dateModeScore,'entry date default is non-inferential');run(`state.episodes[0].entryDateMode='latest_evidence'`);
// Linked episodes never populate the current monitoring queue.
run(`const prior=makeEpisode('r','Prior','2025-01-01T00:00:00Z');prior.id='prior-monitor';prior.trackingMode='retrospective';state.episodes.push(prior);state.observations.push({id:'prior-thirst',episodeId:'prior-monitor',findingId:'thirst_increased',status:'present',present:true,time:'2025-01-02T00:00:00Z',severity:'high',confidence:'high',notes:''});state.episodes.find(e=>e.id==='re').linkedEpisodeIds=['prior-monitor'];`);assert(!run(`monitoringCandidates().some(x=>x.last.episodeId==='prior-monitor')`),'linked history excluded from current monitoring queue');
// Urgency age is based on the triggering finding, not unrelated newer context.
run(`state.observations=[{id:'u-old',episodeId:state.settings.activeEpisodeId,findingId:'urine_none',present:true,status:'present',time:'2025-01-01T00:00:00Z',severity:'high',confidence:'high',notes:''}];state.studies=[{id:'st-new',petId:state.settings.activePetId,episodeId:state.settings.activeEpisodeId,type:'ultrasound',time:new Date().toISOString(),interpretation:'normal',summary:'new unrelated study'}];`);
assert(run(`urgencyAlerts()[0].triggerTime`).startsWith('2025-01-01'),'urgency carries trigger time');
assert(run(`urgencyIsHistorical(urgencyAlerts()[0])`)===true,'old urgent finding remains historical despite newer context');
// Numeric trends never combine unlike units.
run(`state.clinicalMeasurements=[
{id:'w1',petId:state.settings.activePetId,episodeId:state.settings.activeEpisodeId,templateId:'body_weight',time:'2025-01-01T00:00:00Z',value:'10',unit:'lb',confidence:'high',useInModel:true},
{id:'w2',petId:state.settings.activePetId,episodeId:state.settings.activeEpisodeId,templateId:'body_weight',time:'2025-01-10T00:00:00Z',value:'9.5',unit:'lb',confidence:'high',useInModel:true},
{id:'w3',petId:state.settings.activePetId,episodeId:state.settings.activeEpisodeId,templateId:'body_weight',time:'2025-01-20T00:00:00Z',value:'4.1',unit:'kg',confidence:'high',useInModel:true}
];`);
assert(run(`quantitativeTrendEvidence().length`)===0,'mixed units cannot create a numeric trend');
run(`state.clinicalMeasurements.push({id:'w4',petId:state.settings.activePetId,episodeId:state.settings.activeEpisodeId,templateId:'body_weight',time:'2025-01-20T00:00:00Z',value:'9.0',unit:'lb',confidence:'high',useInModel:true})`);
assert(run(`quantitativeTrendEvidence().some(e=>e.findingId==='weight_loss'&&e.unit==='lb')`),'same-unit series can derive trend evidence');
console.log('PASS urgency trigger-time aging');
console.log('PASS unit-safe quantitative trends');
