import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';
let code=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8').replace(/\ninit\(\);\s*$/,'\n');
const k=JSON.parse(fs.readFileSync(new URL('../data/cat-knowledge-v0.7.json',import.meta.url),'utf8'));
const ctx={console,crypto:crypto.webcrypto,setTimeout,clearTimeout,structuredClone,Intl,Date,Math,JSON,Map,Set,URL,Blob};vm.createContext(ctx);vm.runInContext(code,ctx);
vm.runInContext(`knowledge=${JSON.stringify(k)};state=defaultState();state.pets[0]={...state.pets[0],id:'demo-pet',name:'Mira',sex:'female',birthDate:'2016-05-12'};state.settings.activePetId='demo-pet';const ep=state.episodes[0];ep.id='demo-ep';ep.petId='demo-pet';ep.title='Chronic GI / hepatobiliary workup';ep.start='2025-03-01T12:00:00Z';ep.trackingMode='retrospective';state.settings.activeEpisodeId='demo-ep';state.observations=[
{id:'o1',episodeId:'demo-ep',findingId:'appetite_reduced',status:'present',present:true,time:'2025-03-02T12:00:00Z',severity:'high',confidence:'high',notes:''},
{id:'o2',episodeId:'demo-ep',findingId:'weight_loss',status:'present',present:true,time:'2025-03-05T12:00:00Z',severity:'high',confidence:'high',notes:''},
{id:'o3',episodeId:'demo-ep',findingId:'vomit_repeated',status:'present',present:true,time:'2025-03-08T12:00:00Z',severity:'medium',confidence:'high',notes:''},
{id:'o4',episodeId:'demo-ep',findingId:'chronic_course',status:'present',present:true,time:'2025-03-15T12:00:00Z',severity:'medium',confidence:'high',notes:''}
];state.workupEvents=[
{id:'w1',petId:'demo-pet',episodeId:'demo-ep',conditionId:'ibd_chronic_enteropathy',status:'under_consideration',time:'2025-03-10T12:00:00Z',source:'veterinarian',certainty:'medium',useInModel:false,strength:'moderate',basisType:'none',basisId:'',rationale:'Chronic gastrointestinal signs kept IBD/chronic enteropathy on the working differential.',notes:''},
{id:'w2',petId:'demo-pet',episodeId:'demo-ep',conditionId:'pancreatitis',status:'less_likely',time:'2025-03-14T12:00:00Z',source:'specialist',certainty:'high',useInModel:true,strength:'moderate',basisType:'none',basisId:'',rationale:'Subsequent workup made pancreatitis less consistent with the overall case.',notes:''},
{id:'w3',petId:'demo-pet',episodeId:'demo-ep',conditionId:'ibd_chronic_enteropathy',status:'ruled_out',time:'2025-03-18T12:00:00Z',source:'specialist',certainty:'high',useInModel:true,strength:'strong',basisType:'none',basisId:'',rationale:'Further diagnostic workup excluded IBD from the active differential.',notes:''},
{id:'w4',petId:'demo-pet',episodeId:'demo-ep',conditionId:'gi_lymphoma',status:'supported',time:'2025-03-19T12:00:00Z',source:'specialist',certainty:'medium',useInModel:true,strength:'moderate',basisType:'none',basisId:'',rationale:'The remaining pattern shifted attention toward an infiltrative/neoplastic process.',notes:''}
];`,ctx);
const content=vm.runInContext('renderDifferentialPage()',ctx);const css=fs.readFileSync(new URL('../styles.css',import.meta.url),'utf8');
const html=`<!doctype html><html><head><meta charset="utf-8"><style>${css}</style><style>body{overflow:auto}.app-shell{min-height:100vh}.sidebar{position:fixed;width:215px}.app-shell main{margin-left:215px}.topbar{position:static}.content{max-width:1450px}button{pointer-events:none}</style></head><body><div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">B</div><div><strong>Bayesian</strong><span>Symptom Tracker</span></div></div><nav><button><span>◫</span> Dashboard</button><button><span>◎</span> Monitoring</button><button><span>∿</span> Model</button><button class="active"><span>⇄</span> Differential</button><button><span>✓</span> Validation</button><button><span>⚙</span> Settings</button></nav></aside><main><header class="topbar"><div><h1>Differential workup</h1><p>Record how the clinical differential narrows over time without rewriting raw evidence.</p></div><div class="top-actions"><button class="ghost">Mira ▾</button><button class="ghost">Chronic GI / hepatobiliary workup ▾</button></div></header><section class="content">${content}</section></main></div></body></html>`;
fs.mkdirSync(new URL('../docs/screenshots/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('../docs/differential-preview.html',import.meta.url),html);
